import { User } from './models/users';

export const USERS: User[] = [
  {
    id: 11,
    status: 'Active',
    email: 'someuser001@gmail.com',
    username: 'someuser001',
    password: '12345678',
    userType: 'Individual',
  },
  {
    id: 12,
    status: 'Active',
    email: 'someuser002@gmail.com',
    username: 'someuser002',
    password: '12345678',
    userType: 'Individual',
  },
  {
    id: 13,
    status: 'Active',
    email: 'someAgent001@gmail.com',
    username: 'someAgent001',
    password: '12345678',
    userType: 'Agent',
  },
  {
    id: 14,
    status: 'Active',
    email: 'someAgent002@gmail.com',
    username: 'someAgent002',
    password: '12345678',
    userType: 'Agent',
  },
  {
    id: 15,
    status: 'Active',
    email: 'someAgent003@gmail.com',
    username: 'someAgent003',
    password: '12345678',
    userType: 'Agent',
  },
  {
    id: 16,
    status: 'Active',
    username: 'grimreaper666',
    password: '$2b$10$G0UVSOOIKi0YbRSydPFpYu3Yj7L5vdUm995H9yOIYQvhqLBa/F6/K',
    email: 'grimreaper666@mail.com',
    userType: 'Individual',
  },
  {
    id: 17,
    status: 'Active',
    username: 'grimreaper6667',
    password: '$2b$10$/KqZwiY9aZIg3D1dJjQiMelRXdE6plFJazAl0FHIJIbEf.hYLefAu',
    email: 'grimreaper6667@mail.com',
    userType: 'Individual',
  },
];
